Feat: Ad GPT in markup mode
gravity-ui/markdown-editor pull request #404
Opened 2024-10-03 11:59 UTC by ReFFaT

2024-10-03 14:18 UTC, d3m1d0v requested changes

2024-10-03 14:18 UTC, d3m1d0v commented on src/extensions/yfm/GPT/MarkupGpt/commands.ts
> +export const showMarkupGptExample = (view: EditorView) => {
remove "example" suffix or replace it with something else

2024-10-03 14:18 UTC, d3m1d0v commented on src/extensions/yfm/GPT/MarkupGpt/commands.ts
> +export const hideMarkupGptExample = (view: EditorView) => {
remove "example" suffix or replace it with something else

2024-10-03 14:18 UTC, d3m1d0v commented on src/extensions/yfm/GPT/MarkupGpt/effects.ts
> +export const HideMarkupGptExampleEffect = StateEffect.define();
remove "example" suffix or replace it with something else

2024-10-03 14:18 UTC, d3m1d0v commented on src/extensions/yfm/GPT/MarkupGpt/plugin.ts
> +const DECO_CLASS_NAME = 'react-popup-example-deco';
Specify relevant value

2024-10-03 14:18 UTC, d3m1d0v commented on src/extensions/yfm/GPT/MarkupGpt/plugin.ts
> +                    .createItem('react-popup-example-in-markup-mode', () => this.renderPopup());
Specify relevant value for first argument

2024-10-03 14:18 UTC, d3m1d0v commented on src/extensions/yfm/GPT/MarkupGpt/toolbar.ts
> +    title: 'Help with text',
i18n?

2024-10-03 14:18 UTC, d3m1d0v commented on src/extensions/yfm/GPT/MarkupGpt/toolbar.ts
> +    id: 'react-popup-example',
Set relevant id

2024-10-03 14:18 UTC, d3m1d0v commented on src/extensions/yfm/GPT/MarkupGpt/toolbar.ts
> +    id: 'react-popup-example',
remove "example"

2024-10-03 14:18 UTC, d3m1d0v commented on src/extensions/yfm/GPT/MarkupGpt/popup.tsx
> +        <Portal>
Unnecessary `<Portal>` wrapper

2024-10-03 14:18 UTC, d3m1d0v commented on src/extensions/yfm/GPT/MarkupGpt/plugin.ts
> +                this.state = update.state;
It is unnecessary to save the entire state, it is enough to save only `from` and `to` from the selection

2024-10-03 14:18 UTC, d3m1d0v commented on src/extensions/yfm/GPT/MarkupGpt/plugin.ts
> +export function mGptExamplePlugin(gptProps: GptWidgetOptions) {
"example"

2024-10-14 15:24 UTC, makhnatkin approved these changes

2024-10-15 10:19 UTC, d3m1d0v approved these changes

2024-10-15 10:19 UTC, d3m1d0v commented on src/extensions/additional/GPT/MarkupGpt/plugin.ts
> +                hideMarkupGpt(this._view);
You can add `{effects: [HideMarkupGptEffect.of(null)]}` to previous transaction and not call dispatch twice.

2024-10-15 11:17 UTC, makhnatkin approved these changes

2024-10-15 11:17 UTC, merged